-- Verbatim source metadata for an investigation, as a JSON blob.
--
-- Gemma keeps only a converted subset of a GEO record: GeoFamilyParser parses the whole
-- SOFT family file, and GeoConverterImpl writes the parts that map onto the relational
-- model (title, summaries, characteristics, protocols, factors) and drops the rest —
-- sample dataProcessing / hybProtocol / scanProtocol / supplementaryFiles / status /
-- submissionDate are parsed and never persisted, and characteristic text over 255
-- characters is truncated to 200. The only full copy is the GSE*.soft.gz on disk, which
-- is a filesystem cache, not queryable. This column gives the record a home in the
-- database, mirroring what the curation agents already keep offline.
--
-- Gemma stores the blob opaquely — it never parses or queries it — so the JSON schema is
-- a contract with the agents repo and can evolve without a further migration. Same
-- arrangement as CHARACTERISTIC.SUPPORTING_EVIDENCE (V22). Schema v1 was agreed with CAB
-- on 2026-08-09 (handoff GEMMA_REPLY_2026_08_09_SOURCE_METADATA_BLOB.md); the payload
-- carries its own schemaVersion as well.
--
-- The schema version is a COLUMN, not only a key inside the payload. The V22 analogy only
-- goes so far: FindingEvidence carries no version and is additive-only, which is precisely
-- why it evolves without migrations. This payload is versioned and Gemma is a
-- version-aware writer of it, so v0 and v1 rows coexist. Keeping the version queryable
-- makes "which rows are still v0?" a WHERE clause instead of a full-table JSON parse, and
-- makes a batched backfill ordinary SQL. It cannot be retrofitted cheaply once the column
-- is populated.
--
-- ADDITIVE, NOT A RENAME — this is the part to not undo.
--
-- The obvious form of this migration renames PREBOARDED_IDENTIFYING_METADATA, since that
-- column is already on INVESTIGATION and is the same kind of payload. It must not:
-- production Gemma 1.32.x shares this database and maps that column in
-- Investigation.hbm.xml. INVESTIGATION is SINGLE_TABLE inheritance, so a mapped subclass
-- property lands in the SQL generated for any polymorphic Investigation query — renaming
-- the column breaks the deployed 1.0 application on an unknown column, and does so at
-- mapping-resolution time, which means an empty table does not save us.
--
-- Adding instead costs one redundant column until cutover and nothing else. There is no
-- data to carry across: the preboarded table is empty, so the rename would have preserved
-- nothing. Both applications keep working in any deploy order, which the rename version
-- could not offer — patched-1.0-first and migration-first each left one side broken.
--
-- AT CUTOVER, once 1.32.x is retired: drop PREBOARDED_IDENTIFYING_METADATA. Until then it
-- stays, unmapped by Gemma 2.0 and still mapped by 1.0.
--
-- Note ADD COLUMN rebuilds INVESTIGATION on the 5.7 dialect (no INSTANT ADD COLUMN before
-- 8.0.12). Online via INPLACE, but it takes a metadata lock at each end and needs the disk
-- headroom, so run it when the table is not under a long transaction.
ALTER TABLE INVESTIGATION
    ADD COLUMN SOURCE_METADATA LONGTEXT NULL,
    ADD COLUMN SOURCE_METADATA_SCHEMA_VERSION SMALLINT NULL;
