name: Build Gemma

on:
  push:
    branches:
    - master
    - development
    - hotfix-*
    - release-*
  pull_request:
    branches:
    - master
    - development
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - name: Build with Maven
      run: mvn -B package -DexcludedGroups=SlowTest
