-- $Id$
-- Triggers to fill in denormalized fields
-- This is designed to be run from a configuration that defines the delimiter for commands to be '|'. If you run it by hand execute 'DELIMITER |' first.

CREATE TRIGGER humanCoexpTrigger BEFORE INSERT ON HUMAN_PROBE_CO_EXPRESSION
  FOR EACH ROW BEGIN  
    select dedvFirst.DESIGN_ELEMENT_FK, dedvSecond.DESIGN_ELEMENT_FK INTO @firstDEDV, @secondDEDV FROM PROCESSED_EXPRESSION_DATA_VECTOR dedvFirst, PROCESSED_EXPRESSION_DATA_VECTOR dedvSecond WHERE NEW.FIRST_VECTOR_FK=dedvFirst.ID AND NEW.SECOND_VECTOR_FK=dedvSecond.ID;
    SET NEW.FIRST_DESIGN_ELEMENT_FK = @firstDEDV;
    SET NEW.SECOND_DESIGN_ELEMENT_FK = @secondDEDV;
   END;|
   
CREATE TRIGGER mouseCoexpTrigger BEFORE INSERT ON MOUSE_PROBE_CO_EXPRESSION
  FOR EACH ROW BEGIN  
    select dedvFirst.DESIGN_ELEMENT_FK, dedvSecond.DESIGN_ELEMENT_FK INTO  @firstDEDV, @secondDEDV FROM PROCESSED_EXPRESSION_DATA_VECTOR dedvFirst, PROCESSED_EXPRESSION_DATA_VECTOR dedvSecond WHERE NEW.FIRST_VECTOR_FK=dedvFirst.ID AND NEW.SECOND_VECTOR_FK=dedvSecond.ID;
    SET NEW.FIRST_DESIGN_ELEMENT_FK = @firstDEDV;
    SET NEW.SECOND_DESIGN_ELEMENT_FK = @secondDEDV;
   END;|
   
CREATE TRIGGER ratCoexpTrigger BEFORE INSERT ON RAT_PROBE_CO_EXPRESSION
  FOR EACH ROW BEGIN  
    select dedvFirst.DESIGN_ELEMENT_FK, dedvSecond.DESIGN_ELEMENT_FK INTO @firstDEDV, @secondDEDV FROM PROCESSED_EXPRESSION_DATA_VECTOR dedvFirst, PROCESSED_EXPRESSION_DATA_VECTOR dedvSecond WHERE NEW.FIRST_VECTOR_FK=dedvFirst.ID AND NEW.SECOND_VECTOR_FK=dedvSecond.ID;
    SET NEW.FIRST_DESIGN_ELEMENT_FK = @firstDEDV;
    SET NEW.SECOND_DESIGN_ELEMENT_FK = @secondDEDV;
   END;|
   
CREATE TRIGGER otherCoexpTrigger BEFORE INSERT ON OTHER_PROBE_CO_EXPRESSION
  FOR EACH ROW BEGIN  
    select dedvFirst.DESIGN_ELEMENT_FK, dedvSecond.DESIGN_ELEMENT_FK INTO  @firstDEDV, @secondDEDV FROM PROCESSED_EXPRESSION_DATA_VECTOR dedvFirst, PROCESSED_EXPRESSION_DATA_VECTOR dedvSecond WHERE NEW.FIRST_VECTOR_FK=dedvFirst.ID AND NEW.SECOND_VECTOR_FK=dedvSecond.ID;
    SET NEW.FIRST_DESIGN_ELEMENT_FK = @firstDEDV;
    SET NEW.SECOND_DESIGN_ELEMENT_FK = @secondDEDV;
   END;|
