// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: Gemma Enumeration.vsl in andromda-java-cartridge.
// $Id$
package ubic.gemma.model.genome.gene;

/**
 * 
 */
public class GeneProductType implements java.io.Serializable, Comparable<GeneProductType> {
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8731014426320800790L;

    /**
     * 
     */
    public static final GeneProductType PROTEIN = new GeneProductType( "PROTEIN" );

    /**
     * 
     */
    public static final GeneProductType RNA = new GeneProductType( "RNA" );

    private static final java.util.Map<String, GeneProductType> values = new java.util.LinkedHashMap<String, GeneProductType>(
            2, 1 );

    /**
     * Creates an instance of GeneProductType from <code>value</code>.
     * 
     * @param value the value to create the GeneProductType from.
     */
    public static GeneProductType fromString( String value ) {
        final GeneProductType typeValue = values.get( value );
        if ( typeValue == null ) {
            /*
             * Customization to permit database values to change before code does. Previously this would throw an
             * exception.
             */
            // throw new IllegalArgumentException("invalid value '" + value + "', possible values are: " + literals);
            return null;
        }
        return typeValue;
    }

    /**
     * Returns an unmodifiable list containing the literals that are known by this enumeration.
     * 
     * @return A List containing the actual literals defined by this enumeration, this list can not be modified.
     */
    public static java.util.List<String> literals() {
        return literals;
    }

    /**
     * Returns an unmodifiable list containing the names of the literals that are known by this enumeration.
     * 
     * @return A List containing the actual names of the literals defined by this enumeration, this list can not be
     *         modified.
     */
    public static java.util.List<String> names() {
        return names;
    }

    /**
     * Returns an unmodifiable list containing the actual enumeration instance values.
     * 
     * @return A List containing the actual enumeration instance values.
     */
    public static java.util.List<GeneProductType> values() {
        return valueList;
    }

    private String value;

    private static java.util.List<String> literals = new java.util.ArrayList<String>( 2 );

    private static java.util.List<String> names = new java.util.ArrayList<String>( 2 );

    private static java.util.List<GeneProductType> valueList = new java.util.ArrayList<GeneProductType>( 2 );

    /**
     * Initializes the values.
     */
    static {
        values.put( PROTEIN.value, PROTEIN );
        valueList.add( PROTEIN );
        literals.add( PROTEIN.value );
        names.add( "PROTEIN" );
        values.put( RNA.value, RNA );
        valueList.add( RNA );
        literals.add( RNA.value );
        names.add( "RNA" );
        valueList = java.util.Collections.unmodifiableList( valueList );
        literals = java.util.Collections.unmodifiableList( literals );
        names = java.util.Collections.unmodifiableList( names );
    }

    /**
     * The default constructor allowing super classes to access it.
     */
    protected GeneProductType() {
    }

    private GeneProductType( String value ) {
        this.value = value;
    }

    /**
     * @see Comparable#compareTo(Object)
     */
    @Override
    public int compareTo( GeneProductType that ) {
        return ( this == that ) ? 0 : this.getValue().compareTo( ( that ).getValue() );
    }

    /**
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals( Object object ) {
        return ( this == object )
                || ( object instanceof GeneProductType && ( ( GeneProductType ) object ).getValue().equals(
                        this.getValue() ) );
    }

    /**
     * Gets the underlying value of this type safe enumeration.
     * 
     * @return the underlying value.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * @see Object#hashCode()
     */
    @Override
    public int hashCode() {
        return this.getValue().hashCode();
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return String.valueOf( value );
    }

    /**
     * This method allows the deserialization of an instance of this enumeration type to return the actual instance that
     * will be the singleton for the JVM in which the current thread is running.
     * <p>
     * Doing this will allow users to safely use the equality operator <code>==</code> for enumerations because a
     * regular deserialized object is always a newly constructed instance and will therefore never be an existing
     * reference; it is this <code>readResolve()</code> method which will intercept the deserialization process in order
     * to return the proper singleton reference.
     * <p>
     * This method is documented here: <a
     * href="http://java.sun.com/j2se/1.3/docs/guide/serialization/spec/input.doc6.html">Java Object Serialization
     * Specification</a>
     */
    private Object readResolve() {
        return GeneProductType.fromString( this.value );
    }
}