alter table CHARACTERISTIC
    add index CHARACTERISTIC_VALUE_URI_VALUE (VALUE_URI, `VALUE`);
alter table CHARACTERISTIC
    add index CHARACTERISTIC_CATEGORY_URI_CATEGORY_VALUE_URI_VALUE (CATEGORY_URI, CATEGORY, VALUE_URI, `VALUE`);
alter table CHARACTERISTIC
    add index CHARACTERISTIC_PREDICATE_URI_PREDICATE (PREDICATE_URI, PREDICATE);
alter table CHARACTERISTIC
    add index CHARACTERISTIC_OBJECT_URI_OBJECT (OBJECT_URI, OBJECT);
alter table CHARACTERISTIC
    add index CHARACTERISTIC_SECOND_PREDICATE_URI_SECOND_PREDICATE (SECOND_PREDICATE_URI, SECOND_PREDICATE);
alter table CHARACTERISTIC
    add index CHARACTERISTIC_SECOND_OBJECT_URI_SECOND_OBJECT (SECOND_OBJECT_URI, SECOND_OBJECT);

create index EE2C_CATEGORY_URI_CATEGORY_VALUE_URI_VALUE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (CATEGORY_URI, CATEGORY, VALUE_URI, `VALUE`);
create index EE2C_VALUE_URI_VALUE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (VALUE_URI, `VALUE`);
create index EE2C_PREDICATE_URI_PREDICATE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (PREDICATE_URI, PREDICATE);
create index EE2C_OBJECT_URI_OBJECT on EXPRESSION_EXPERIMENT2CHARACTERISTIC (OBJECT_URI, OBJECT);
create index EE2C_SECOND_PREDICATE_URI_SECOND_PREDICATE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_PREDICATE_URI, SECOND_PREDICATE);
create index EE2C_SECOND_OBJECT_URI_SECOND_OBJECT on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_OBJECT_URI, SECOND_OBJECT);
