/*
 * The Gemma project.
 * 
 * Copyright (c) 2006-2007 University of British Columbia
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringDao.vsl in andromda-spring-cartridge.
//
package ubic.gemma.model.common.auditAndSecurity;

import ubic.gemma.persistence.BaseDao;

/**
 * @see ubic.gemma.model.common.auditAndSecurity.UserGroup
 */
public interface UserGroupDao extends BaseDao<UserGroup> {

    /**
     * <p>
     * Does the same thing as {@link #findByUserGroupName(java.lang.String)} with an additional flag called
     * <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then finder results will
     * <strong>NOT</strong> be transformed during retrieval. If this flag is any of the other constants defined here
     * then finder results <strong>WILL BE</strong> passed through an operation which can optionally transform the
     * entities (into value objects for example). By default, transformation does not occur.
     * </p>
     */
    public Object findByUserGroupName( int transform, java.lang.String name );

    /**
     * <p>
     * Does the same thing as {@link #findByUserGroupName(boolean, java.lang.String)} with an additional argument called
     * <code>queryString</code>. This <code>queryString</code> argument allows you to override the query string defined
     * in {@link #findByUserGroupName(int, java.lang.String name)}.
     * </p>
     */
    public Object findByUserGroupName( int transform, String queryString, java.lang.String name );

    /**
     * 
     */
    public ubic.gemma.model.common.auditAndSecurity.UserGroup findByUserGroupName( java.lang.String name );

    /**
     * <p>
     * Does the same thing as {@link #findByUserGroupName(java.lang.String)} with an additional argument called
     * <code>queryString</code>. This <code>queryString</code> argument allows you to override the query string defined
     * in {@link #findByUserGroupName(java.lang.String)}.
     * </p>
     */
    public ubic.gemma.model.common.auditAndSecurity.UserGroup findByUserGroupName( String queryString,
            java.lang.String name );

}
