
-- Changes for keeping track of original phenotype and way the evidence was mapped
ALTER TABLE PHENOTYPE_ASSOCIATION ADD MAPPING_TYPE VARCHAR(255) DEFAULT NULL AFTER EVIDENCE_CODE;
ALTER TABLE PHENOTYPE_ASSOCIATION ADD ORIGINAL_PHENOTYPE VARCHAR(255) DEFAULT NULL AFTER MAPPING_TYPE;
