ALTER TABLE ANALYSIS DROP COLUMN STATUS_FK;
ALTER TABLE BIBLIOGRAPHIC_REFERENCE DROP COLUMN STATUS_FK;
ALTER TABLE BIO_ASSAY DROP COLUMN STATUS_FK;
ALTER TABLE BIO_MATERIAL DROP COLUMN STATUS_FK;
ALTER TABLE CHARACTERISTIC DROP COLUMN STATUS_FK;
ALTER TABLE CHROMOSOME_FEATURE DROP COLUMN STATUS_FK;
ALTER TABLE CONTACT DROP COLUMN STATUS_FK;
ALTER TABLE EXPERIMENTAL_DESIGN DROP COLUMN STATUS_FK;
ALTER TABLE EXPERIMENTAL_FACTOR DROP COLUMN STATUS_FK;
ALTER TABLE EXPRESSION_EXPERIMENT_SET DROP COLUMN STATUS_FK;
ALTER TABLE EXTERNAL_DATABASE DROP COLUMN STATUS_FK;
ALTER TABLE GENE_SET DROP COLUMN STATUS_FK;
ALTER TABLE PARAMETERIZABLE DROP COLUMN STATUS_FK;
ALTER TABLE PROTOCOL DROP COLUMN STATUS_FK;
ALTER TABLE TREATMENT DROP COLUMN STATUS_FK;
ALTER TABLE USER_GROUP DROP COLUMN STATUS_FK;

ALTER TABLE PHENOTYPE_ASSOCIATION DROP COLUMN STATUS_FK;
