
create table COEXP_CORRELATION_DISTRIBUTION (ID BIGINT not null auto_increment, NUM_BINS INTEGER not null, BIN_COUNTS MEDIUMBLOB not null, primary key (ID));

alter table ANALYSIS add column COEXP_CORRELATION_DISTRIBUTION_FK BIGINT;
alter table ANALYSIS add index FKF19622DC6BCD8439 (COEXP_CORRELATION_DISTRIBUTION_FK), add constraint FKF19622DC6BCD8439 foreign key (COEXP_CORRELATION_DISTRIBUTION_FK) references COEXP_CORRELATION_DISTRIBUTION (ID);
