-- H2 sibling of mysql/V10__investigation_workflow_state.sql.
-- See that file for motivation and backfill-deferral notes.

ALTER TABLE INVESTIGATION
    ADD COLUMN WORKFLOW_STATE VARCHAR(32) DEFAULT 'Loaded' NOT NULL;
ALTER TABLE INVESTIGATION
    ADD COLUMN WORKFLOW_STATE_ENTERED_AT DATETIME NULL;

CREATE INDEX IF NOT EXISTS INVESTIGATION_WORKFLOW_STATE ON INVESTIGATION (WORKFLOW_STATE);
