-- H2 sibling of mysql/V11__agent_proposal_skeleton_investigation.sql.
-- See that file for motivation. Differences:
--   * H2 lacks the native JSON type; PAYLOAD_JSON is CLOB. Hibernate's
--     MaterializedClobType reads/writes the same String to both.
--   * H2 unique key syntax uses CONSTRAINT ... UNIQUE (...) outside the
--     UNIQUE KEY shorthand.
--   * H2 lacks the inline INDEX shorthand inside CREATE TABLE; uses CREATE
--     INDEX statements after.

ALTER TABLE INVESTIGATION
    ADD COLUMN SKELETON_ACCESSION VARCHAR(255) NULL;
ALTER TABLE INVESTIGATION
    ADD COLUMN SKELETON_SOURCE VARCHAR(32) NULL;
ALTER TABLE INVESTIGATION
    ADD COLUMN SKELETON_IDENTIFYING_METADATA CLOB NULL;

CREATE INDEX IF NOT EXISTS INVESTIGATION_SKELETON_ACCESSION ON INVESTIGATION (SKELETON_ACCESSION);

CREATE TABLE AGENT_PROPOSAL (
    ID                  BIGINT       NOT NULL AUTO_INCREMENT,
    INVESTIGATION_FK    BIGINT       NOT NULL,
    RUN_ID              VARCHAR(255) NOT NULL,
    AGENT_VERSION       VARCHAR(255) NULL,
    MODEL               VARCHAR(255) NULL,
    RAN_AT              DATETIME     NULL,
    PAYLOAD_JSON        CLOB         NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_AGENT_PROPOSAL_INVESTIGATION
        FOREIGN KEY (INVESTIGATION_FK) REFERENCES INVESTIGATION (ID),
    CONSTRAINT UK_AGENT_PROPOSAL_INVESTIGATION_RUN
        UNIQUE (INVESTIGATION_FK, RUN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_AGENT_PROPOSAL_INVESTIGATION ON AGENT_PROPOSAL (INVESTIGATION_FK);
