-- H2 sibling of mysql/V12__curation_draft.sql. Differences:
--   * H2 lacks LONGTEXT; CLOB is the equivalent.
--   * H2 lacks the inline INDEX shorthand inside CREATE TABLE; uses
--     CREATE INDEX after.
--   * H2 unique key syntax uses CONSTRAINT ... UNIQUE (...) outside the
--     UNIQUE KEY shorthand.
--   * H2 does not honour `DESC` inside CREATE INDEX (parsed but ignored
--     since H2 walks both directions on btrees) — we drop the keyword.

CREATE TABLE CURATION_DRAFT (
    ID                      BIGINT   NOT NULL AUTO_INCREMENT,
    INVESTIGATION_FK        BIGINT   NOT NULL,
    CURATOR_FK              BIGINT   NOT NULL,
    PAYLOAD_JSON            CLOB     NOT NULL,
    PROPOSAL_FK             BIGINT   NULL,
    PROPOSAL_SNAPSHOT_JSON  CLOB     NULL,
    PARKED_ELEMENTS         CLOB     NULL,
    STARTED_AT              DATETIME NOT NULL,
    LAST_EDITED_AT          DATETIME NOT NULL,
    FINALIZED_AT            DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CURATION_DRAFT_INVESTIGATION
        FOREIGN KEY (INVESTIGATION_FK) REFERENCES INVESTIGATION (ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_CURATION_DRAFT_CURATOR
        FOREIGN KEY (CURATOR_FK) REFERENCES CONTACT (ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_CURATION_DRAFT_PROPOSAL
        FOREIGN KEY (PROPOSAL_FK) REFERENCES AGENT_PROPOSAL (ID)
        ON DELETE SET NULL,
    CONSTRAINT UQ_CURATION_DRAFT_PER_CURATOR_EE
        UNIQUE (INVESTIGATION_FK, CURATOR_FK)
);

CREATE INDEX IF NOT EXISTS IDX_CURATION_DRAFT_CURATOR_RECENT
    ON CURATION_DRAFT (CURATOR_FK, LAST_EDITED_AT);

CREATE INDEX IF NOT EXISTS IDX_CURATION_DRAFT_PROPOSAL
    ON CURATION_DRAFT (PROPOSAL_FK);
