-- h2 mirror of mysql V16__user_soft_delete.sql.

ALTER TABLE CONTACT
    ADD COLUMN DELETED_AT TIMESTAMP NULL;

ALTER TABLE CONTACT
    ADD COLUMN DELETED_BY VARCHAR(255) NULL;

CREATE INDEX CONTACT_DELETED_AT_IDX ON CONTACT (DELETED_AT);
