-- h2 mirror of mysql/V17__geo_scrape_watermark.sql. Paul-approved 2026-05-23.

CREATE TABLE GEO_SCRAPE_WATERMARK (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SCANNED_AT TIMESTAMP NOT NULL,
    SCAN_FROM TIMESTAMP NULL,
    SCAN_TO TIMESTAMP NULL,
    RECORDS_SCANNED INT NOT NULL DEFAULT 0,
    RECORDS_MATCHED INT NOT NULL DEFAULT 0,
    CRITERIA_APPLIED VARCHAR(1024) NULL,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'COMPLETED',
    ERROR_MESSAGE CLOB NULL
);

CREATE INDEX IF NOT EXISTS GEO_SCRAPE_WATERMARK_SCANNED_AT_IDX ON GEO_SCRAPE_WATERMARK (SCANNED_AT);

ALTER TABLE INVESTIGATION
    ADD COLUMN PREBOARDED_MATCHED_CRITERIA CLOB NULL;
