-- H2 counterpart of mysql/V23__scde_cascade_on_parent_delete.sql. See that file
-- for the full rationale (reverse compatibility with production 1.32.x sharing
-- the same database).
--
-- Differences from the MySQL variant:
--   * H2 spells the drop as DROP CONSTRAINT, not DROP FOREIGN KEY.
--   * H2 has no multi-clause ALTER TABLE, so each constraint is its own
--     statement.

ALTER TABLE SINGLE_CELL_DIMENSION_EXPERIMENT DROP CONSTRAINT FK_SCDE_EXPRESSION_EXPERIMENT;
ALTER TABLE SINGLE_CELL_DIMENSION_EXPERIMENT DROP CONSTRAINT FK_SCDE_QUANTITATION_TYPE;
ALTER TABLE SINGLE_CELL_DIMENSION_EXPERIMENT DROP CONSTRAINT FK_SCDE_SINGLE_CELL_DIMENSION;

ALTER TABLE SINGLE_CELL_DIMENSION_EXPERIMENT
    ADD CONSTRAINT FK_SCDE_EXPRESSION_EXPERIMENT
        FOREIGN KEY (EXPRESSION_EXPERIMENT_FK) REFERENCES INVESTIGATION (ID)
        ON DELETE CASCADE;
ALTER TABLE SINGLE_CELL_DIMENSION_EXPERIMENT
    ADD CONSTRAINT FK_SCDE_QUANTITATION_TYPE
        FOREIGN KEY (QUANTITATION_TYPE_FK) REFERENCES QUANTITATION_TYPE (ID)
        ON DELETE CASCADE;
ALTER TABLE SINGLE_CELL_DIMENSION_EXPERIMENT
    ADD CONSTRAINT FK_SCDE_SINGLE_CELL_DIMENSION
        FOREIGN KEY (SINGLE_CELL_DIMENSION_FK) REFERENCES SINGLE_CELL_DIMENSION (ID)
        ON DELETE CASCADE;
