-- See db/migration/mysql/V23__pipeline_job_attempts.sql for the canonical description.
-- The version number differs because the H2 + MySQL migration streams are keyed
-- independently. H2 supports the same ADD COLUMN / ADD CONSTRAINT / ON DELETE SET NULL
-- syntax, so this mirrors the MySQL migration column-for-column.

ALTER TABLE PIPELINE_JOB
    ADD COLUMN ATTEMPT          INT         NOT NULL DEFAULT 1,
    ADD COLUMN RETRY_OF_FK      BIGINT      NULL,
    ADD COLUMN SUPERSEDED_BY_FK BIGINT      NULL,
    ADD COLUMN FAILURE_CLASS    VARCHAR(16) NULL,
    ADD COLUMN PARAMS_JSON      CLOB        NULL;

ALTER TABLE PIPELINE_JOB
    ADD CONSTRAINT CK_PIPELINE_JOB_FAILURE_CLASS
        CHECK (FAILURE_CLASS IS NULL OR FAILURE_CLASS IN ('TRANSIENT', 'PERMANENT', 'UNKNOWN'));

CREATE INDEX IDX_PIPELINE_JOB_BATCH_EE_ATTEMPT
    ON PIPELINE_JOB (BATCH_FK, EXPERIMENT_FK, ATTEMPT);

ALTER TABLE PIPELINE_JOB
    ADD CONSTRAINT FK_PIPELINE_JOB_RETRY_OF
        FOREIGN KEY (RETRY_OF_FK) REFERENCES PIPELINE_JOB (ID) ON DELETE SET NULL;

ALTER TABLE PIPELINE_JOB
    ADD CONSTRAINT FK_PIPELINE_JOB_SUPERSEDED_BY
        FOREIGN KEY (SUPERSEDED_BY_FK) REFERENCES PIPELINE_JOB (ID) ON DELETE SET NULL;
