-- H2 mirror of mysql/V32__annotation_set_triage_rows.sql; see that file for the reasoning.
-- Differences, all mechanical: no ENGINE clause, no inline INDEX shorthand inside
-- CREATE TABLE, and one DROP COLUMN per statement.
CREATE TABLE ANNOTATION_SET_TRIAGE (
    ID                BIGINT        NOT NULL AUTO_INCREMENT,
    ANNOTATION_SET_FK BIGINT        NOT NULL,
    TRIAGE            VARCHAR(16)   NOT NULL,
    JUDGED_BY         VARCHAR(255)  NOT NULL,
    JUDGE_KIND        VARCHAR(16)   NOT NULL,
    JUDGED_AT         DATETIME(3)   NOT NULL,
    NOTE              VARCHAR(1024) NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ANNOTATION_SET_TRIAGE_SET
        FOREIGN KEY (ANNOTATION_SET_FK) REFERENCES ANNOTATION_SET (ID) ON DELETE CASCADE,
    CONSTRAINT UK_ANNOTATION_SET_TRIAGE_SET_JUDGE
        UNIQUE (ANNOTATION_SET_FK, JUDGED_BY)
);

CREATE INDEX IDX_ANNOTATION_SET_TRIAGE_SET_JUDGED
    ON ANNOTATION_SET_TRIAGE (ANNOTATION_SET_FK, JUDGED_AT);

ALTER TABLE ANNOTATION_SET DROP COLUMN TRIAGE;
ALTER TABLE ANNOTATION_SET DROP COLUMN TRIAGED_BY;
ALTER TABLE ANNOTATION_SET DROP COLUMN TRIAGED_AT;
