-- H2 mirror of mysql/V42__annotation_set_dispositions.sql; see that file for the reasoning.
-- Differences, all mechanical: no ENGINE clause and no inline INDEX shorthand inside
-- CREATE TABLE.
CREATE TABLE ANNOTATION_SET_DISPOSITION (
    ID                BIGINT        NOT NULL AUTO_INCREMENT,
    ANNOTATION_SET_FK BIGINT        NOT NULL,
    TARGET_ID         VARCHAR(255)  NOT NULL,
    DISPOSITION       VARCHAR(16)   NOT NULL,
    DECIDED_BY        VARCHAR(255)  NOT NULL,
    JUDGE_KIND        VARCHAR(16)   NOT NULL,
    DECIDED_AT        DATETIME(3)   NOT NULL,
    REASON            VARCHAR(1024) NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ANNOTATION_SET_DISPOSITION_SET
        FOREIGN KEY (ANNOTATION_SET_FK) REFERENCES ANNOTATION_SET (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ANNOTATION_SET_DISPOSITION_SET_TARGET
    ON ANNOTATION_SET_DISPOSITION (ANNOTATION_SET_FK, TARGET_ID, DECIDED_AT);
