-- H2 mirror of mysql/V45__curation_decision.sql; see that file for the reasoning.
-- Differences, all mechanical: no ENGINE clause and no inline INDEX shorthand inside
-- CREATE TABLE.
CREATE TABLE CURATION_DECISION (
    ID                BIGINT        NOT NULL AUTO_INCREMENT,
    INVESTIGATION_FK  BIGINT        NOT NULL,
    DECISION          VARCHAR(16)   NOT NULL,
    DECISION_SCOPE    VARCHAR(16)   NOT NULL,
    DECISION_KEY      VARCHAR(255)  NULL,
    ANNOTATION_SET_FK BIGINT        NULL,
    REASON            VARCHAR(1024) NOT NULL,
    DECIDED_BY        VARCHAR(255)  NOT NULL,
    JUDGE_KIND        VARCHAR(16)   NOT NULL,
    DECIDED_AT        DATETIME(3)   NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CURATION_DECISION_INVESTIGATION
        FOREIGN KEY (INVESTIGATION_FK) REFERENCES INVESTIGATION (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CURATION_DECISION_ANNOTATION_SET
        FOREIGN KEY (ANNOTATION_SET_FK) REFERENCES ANNOTATION_SET (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_CURATION_DECISION_INV_KEY
    ON CURATION_DECISION (INVESTIGATION_FK, DECISION_KEY, DECIDED_AT);
