-- Mirror of mysql/V51__bioassay_extracted_molecule.sql for the H2 test schema.
ALTER TABLE BIO_ASSAY
    ADD COLUMN IF NOT EXISTS EXTRACTED_MOLECULE VARCHAR(32) NULL;
ALTER TABLE BIO_ASSAY
    ADD COLUMN IF NOT EXISTS LIBRARY_SELECTION VARCHAR(255) NULL;
ALTER TABLE BIO_ASSAY
    ADD COLUMN IF NOT EXISTS LIBRARY_STRATEGY VARCHAR(255) NULL;
