Ext.namespace( 'Gemma' );
Gemma.APPNAME = 'Gemma';
Gemma.HOST = 'https://gemma.msl.ubc.ca/';
Gemma.CONTEXT = '';
Gemma.BASEURL = Gemma.HOST + Gemma.CONTEXT;
Gemma.WIKI = 'https://wiki.pavlab.msl.ubc.ca/display/PavLab/Gemma';
Gemma.IMAGEURL = Gemma.CONTEXT + "/images/";
Gemma.ICONURL = Gemma.CONTEXT + "/images/icons/";
Gemma.RECAPTCHA_PUBLIC_KEY = window.recaptchaPublicKey;
Gemma.CONTEXT_PATH = window.Gemma.CONTEXT_PATH || "";
Gemma.GEMBROW_URL = window.gemBrowUrl || "https://gemma.msl.ubc.ca/browse";