import jQuery from 'jquery'
import 'jquery-ui'
import 'jquery-sparkline'
import './jquery.jshowoff'
import 'qtip2'

import './ext/adapter/jquery/ext-jquery-adapter-debug'
import './ext/ext-all-debug'
import './ext/extensions/BrowseButton'
import './ext/extensions/CellToolTips'
import './ext/extensions/CenterLayout'
import './ext/extensions/CheckColumn'
import './ext/extensions/ContainerMask'
import './ext/extensions/Ext.ux.tot2ivn.AccordionVboxLayout'
import './ext/extensions/extjs_fontawesome'
import './ext/extensions/FileUploadField'
import './ext/extensions/InitialTextGridView'
import './ext/extensions/LockingGridView'
import './ext/extensions/Overrides'
import './ext/extensions/PageSizePlugin'
import './ext/extensions/PagingDataStore'
import './ext/extensions/RadioFieldSet'
import './ext/extensions/RowActions'
import './ext/extensions/RowExpander'
import './ext/extensions/SearchField'
import './ext/extensions/Spinner'
import './ext/extensions/SpinnerField'
import './ext/extensions/StatusBar'
import './ext/extensions/TreeGrid'

import './cytoscapejs/cytoscape'
import './cytoscapejs/cytoscape.js-qtip'
import './cytoscapejs/cytoscape.js-panzoom/jquery.cytoscape.js-panzoom'
import './cytoscapejs/cytoscape.js-cxtmenu/jquery.cytoscape.js-cxtmenu'

import './color'
import './canvas-text-functions'
import './discrete-color-range'
import './excanvas'
import './excanvas-text'
import 'flotr2'
import './faces/helvetiker-normal-normal'
import './rsvp'
import './sprintf'
import './arbor'

window.jQuery = jQuery;
window.$ = jQuery;