// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package ubic.gemma.model.genome.gene;

/**
 * 
 */
public class GeneProductValueObject
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1156628868995566223L;

    public GeneProductValueObject()
    {
    }

    public GeneProductValueObject(java.lang.Long id, java.lang.String ncbiId, java.lang.String name, java.lang.Long geneId, java.lang.String type, java.lang.String chromosome, java.lang.String strand, java.lang.Long nucleotideStart, java.lang.Long nucleotideEnd)
    {
        this.id = id;
        this.ncbiId = ncbiId;
        this.name = name;
        this.geneId = geneId;
        this.type = type;
        this.chromosome = chromosome;
        this.strand = strand;
        this.nucleotideStart = nucleotideStart;
        this.nucleotideEnd = nucleotideEnd;
    }

    /**
     * Copies constructor from other GeneProductValueObject
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public GeneProductValueObject(GeneProductValueObject otherBean)
    {
        this(otherBean.getId(), otherBean.getNcbiId(), otherBean.getName(), otherBean.getGeneId(), otherBean.getType(), otherBean.getChromosome(), otherBean.getStrand(), otherBean.getNucleotideStart(), otherBean.getNucleotideEnd());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(GeneProductValueObject otherBean)
    {
        if (otherBean != null)
        {
            this.setId(otherBean.getId());
            this.setNcbiId(otherBean.getNcbiId());
            this.setName(otherBean.getName());
            this.setGeneId(otherBean.getGeneId());
            this.setType(otherBean.getType());
            this.setChromosome(otherBean.getChromosome());
            this.setStrand(otherBean.getStrand());
            this.setNucleotideStart(otherBean.getNucleotideStart());
            this.setNucleotideEnd(otherBean.getNucleotideEnd());
        }
    }

    private java.lang.Long id;

    /**
     * 
     */
    public java.lang.Long getId()
    {
        return this.id;
    }

    public void setId(java.lang.Long id)
    {
        this.id = id;
    }

    private java.lang.String ncbiId;

    /**
     * 
     */
    public java.lang.String getNcbiId()
    {
        return this.ncbiId;
    }

    public void setNcbiId(java.lang.String ncbiId)
    {
        this.ncbiId = ncbiId;
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private java.lang.Long geneId;

    /**
     * 
     */
    public java.lang.Long getGeneId()
    {
        return this.geneId;
    }

    public void setGeneId(java.lang.Long geneId)
    {
        this.geneId = geneId;
    }

    private java.lang.String type;

    /**
     * 
     */
    public java.lang.String getType()
    {
        return this.type;
    }

    public void setType(java.lang.String type)
    {
        this.type = type;
    }

    private java.lang.String chromosome;

    /**
     * 
     */
    public java.lang.String getChromosome()
    {
        return this.chromosome;
    }

    public void setChromosome(java.lang.String chromosome)
    {
        this.chromosome = chromosome;
    }

    private java.lang.String strand;

    /**
     * 
     */
    public java.lang.String getStrand()
    {
        return this.strand;
    }

    public void setStrand(java.lang.String strand)
    {
        this.strand = strand;
    }

    private java.lang.Long nucleotideStart;

    /**
     * 
     */
    public java.lang.Long getNucleotideStart()
    {
        return this.nucleotideStart;
    }

    public void setNucleotideStart(java.lang.Long nucleotideStart)
    {
        this.nucleotideStart = nucleotideStart;
    }

    private java.lang.Long nucleotideEnd;

    /**
     * 
     */
    public java.lang.Long getNucleotideEnd()
    {
        return this.nucleotideEnd;
    }

    public void setNucleotideEnd(java.lang.Long nucleotideEnd)
    {
        this.nucleotideEnd = nucleotideEnd;
    }

    // ubic.gemma.model.genome.gene.GeneProductValueObject value-object java merge-point
}