ALTER TABLE PHYSICAL_LOCATION DROP COLUMN NUCLEOTIDE_END; -- not used
ALTER TABLE PHYSICAL_LOCATION DROP COLUMN EXON_LOCATION_GENE_PRODUCT_FK; -- not used, removed mapping
ALTER TABLE CHROMOSOME_FEATURE DROP COLUMN CDS_PHYSICAL_LOCATION -- not used

