ALTER TABLE INVESTIGATION
    ADD COLUMN PREBOARDED_ACCESSION VARCHAR(255) NULL,
    ADD COLUMN PREBOARDED_SOURCE VARCHAR(32) NULL,
    ADD COLUMN PREBOARDED_IDENTIFYING_METADATA LONGTEXT NULL;
CREATE INDEX INVESTIGATION_PREBOARDED_ACCESSION ON INVESTIGATION (PREBOARDED_ACCESSION);
