alter table ANALYSIS_RESULT_SET
    add column SECOND_BASELINE_GROUP_FK BIGINT references FACTOR_VALUE (ID) after BASELINE_GROUP_FK;

-- populate baselines for interaction terms
update ANALYSIS_RESULT_SET
    join DIFFERENTIAL_EXPRESSION_ANALYSIS_RESULT
    on ANALYSIS_RESULT_SET.ID = DIFFERENTIAL_EXPRESSION_ANALYSIS_RESULT.RESULT_SET_FK
    join CONTRAST_RESULT
    on DIFFERENTIAL_EXPRESSION_ANALYSIS_RESULT.ID = CONTRAST_RESULT.DIFFERENTIAL_EXPRESSION_ANALYSIS_RESULT_FK

    -- first baseline
    join FACTOR_VALUE fv1 on CONTRAST_RESULT.FACTOR_VALUE_FK = fv1.ID
    join ANALYSIS_RESULT_SET b1rs on b1rs.ANALYSIS_FK = ANALYSIS_RESULT_SET.ANALYSIS_FK
    join FACTOR_VALUE b1g
    on b1g.ID = b1rs.BASELINE_GROUP_FK and b1g.EXPERIMENTAL_FACTOR_FK = fv1.EXPERIMENTAL_FACTOR_FK

    -- second baseline
    join FACTOR_VALUE fv2 on CONTRAST_RESULT.SECOND_FACTOR_VALUE_FK = fv2.ID
    join ANALYSIS_RESULT_SET b2rs on b2rs.ANALYSIS_FK = ANALYSIS_RESULT_SET.ANALYSIS_FK
    join FACTOR_VALUE b2g
    on b2g.ID = b2rs.BASELINE_GROUP_FK and b2g.EXPERIMENTAL_FACTOR_FK = fv2.EXPERIMENTAL_FACTOR_FK

set ANALYSIS_RESULT_SET.BASELINE_GROUP_FK        = b1g.ID,
    ANALYSIS_RESULT_SET.SECOND_BASELINE_GROUP_FK = b2g.ID

where ANALYSIS_RESULT_SET.BASELINE_GROUP_FK is null
  and ANALYSIS_RESULT_SET.SECOND_BASELINE_GROUP_FK is null;