-- already run
alter table CHARACTERISTIC ADD COLUMN ORIGINAL_VALUE VARCHAR(255);
-- populate for ones that haven't already been
UPDATE CHARACTERISTIC SET ORIGINAL_VALUE=VALUE WHERE VALUE_URI IS NULL;
-- make nullable
alter table TAXON MODIFY IS_SPECIES tinyint(4);

-- later:
alter table TAXON DROP COLUMN PARENT_TAXON_FK;
alter table TAXON DROP COLUMN IS_SPECIES;
alter table TAXON DROP COLUMN ABBREVIATION;
