alter table EXPRESSION_EXPERIMENT_SET add column ACCESSION_FK BIGINT;
alter table EXPRESSION_EXPERIMENT_SET add constraint ACCESSION_FK unique (ACCESSION_FK);
alter table EXPRESSION_EXPERIMENT_SET add index EXPRESSION_EXPERIMENT_SET_ACCESSION_FKC (ACCESSION_FK), add constraint EXPRESSION_EXPERIMENT_SET_ACCESSION_FKC foreign key (ACCESSION_FK) references DATABASE_ENTRY (ID);
