alter table EXPRESSION_EXPERIMENT2CHARACTERISTIC
    add column PREDICATE            varchar(255),
    add column PREDICATE_URI        varchar(255),
    add column OBJECT               varchar(255),
    add column OBJECT_URI           varchar(255),
    add column SECOND_PREDICATE     varchar(255),
    add column SECOND_PREDICATE_URI varchar(255),
    add column SECOND_OBJECT        varchar(255),
    add column SECOND_OBJECT_URI    varchar(255);

-- add index on URIs, a bit unclear why we didn't have those because we search by them
create index EE2C_CATEGORY_URI on EXPRESSION_EXPERIMENT2CHARACTERISTIC (CATEGORY_URI);
create index EE2C_VALUE_URI on EXPRESSION_EXPERIMENT2CHARACTERISTIC (VALUE_URI);

create index EE2C_PREDICATE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (PREDICATE);
create index EE2C_PREDICATE_URI on EXPRESSION_EXPERIMENT2CHARACTERISTIC (PREDICATE_URI);
create index EE2C_OBJECT on EXPRESSION_EXPERIMENT2CHARACTERISTIC (OBJECT);
create index EE2C_OBJECT_URI on EXPRESSION_EXPERIMENT2CHARACTERISTIC (OBJECT_URI);
create index EE2C_SECOND_PREDICATE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_PREDICATE);
create index EE2C_SECOND_PREDICATE_URI on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_PREDICATE_URI);
create index EE2C_SECOND_OBJECT on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_OBJECT);
create index EE2C_SECOND_OBJECT_URI on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_OBJECT_URI);
