alter table EXPRESSION_EXPERIMENT2CHARACTERISTIC
    add column PREDICATE            varchar(255),
    add column PREDICATE_URI        varchar(255),
    add column OBJECT               varchar(255),
    add column OBJECT_URI           varchar(255),
    add column SECOND_PREDICATE     varchar(255),
    add column SECOND_PREDICATE_URI varchar(255),
    add column SECOND_OBJECT        varchar(255),
    add column SECOND_OBJECT_URI    varchar(255);

create index EE2C_PREDICATE_URI_PREDICATE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (PREDICATE_URI(100), PREDICATE);
create index EE2C_OBJECT_URI_OBJECT on EXPRESSION_EXPERIMENT2CHARACTERISTIC (OBJECT_URI(100), OBJECT);
create index EE2C_SECOND_PREDICATE_URI_SECOND_PREDICATE on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_PREDICATE_URI(100), SECOND_PREDICATE);
create index EE2C_SECOND_OBJECT_URI_SECOND_OBJECT on EXPRESSION_EXPERIMENT2CHARACTERISTIC (SECOND_OBJECT_URI(100), SECOND_OBJECT);

alter table INVESTIGATION add column NUMBER_OF_CELLS integer;