CREATE TABLE `BLACKLIST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `class` varchar(255) NOT NULL,
  `SHORT_NAME` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text,
  `ACCESSION_FK` bigint(20) DEFAULT NULL,
  `REASON` text,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SHORT_NAME` (`SHORT_NAME`),
  UNIQUE KEY `ACCESSION_FK` (`ACCESSION_FK`),
  KEY `FKBLACCESSION` (`ACCESSION_FK`),
  CONSTRAINT `FKBLACCESSION` FOREIGN KEY (`ACCESSION_FK`) REFERENCES `DATABASE_ENTRY` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


ALTER TABLE ARRAY_DESIGN ADD COLUMN ALTERNATIVE_TO_FK bigint(20);
ALTER TABLE ARRAY_DESIGN add constraint FK_ALTERNATIVE_TO_ARRAY_DESIGN FOREIGN KEY(`ALTERNATIVE_TO_FK`) REFERENCES `ARRAY_DESIGN`(`ID`);

UPDATE ARRAY_DESIGN SET TECHNOLOGY_TYPE='SEQUENCING' WHERE TECHNOLOGY_TYPE='NONE' AND SHORT_NAME NOT LIKE "Generic%";
UPDATE ARRAY_DESIGN SET TECHNOLOGY_TYPE='GENELIST' WHERE TECHNOLOGY_TYPE='NONE' AND SHORT_NAME LIKE "Generic%";
