/*
 * The Gemma project
 *
 * Copyright (c) 2026 University of British Columbia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 */
package ubic.gemma.core.analysis.sequence;

import org.junit.jupiter.api.Test;
import ubic.gemma.model.genome.Chromosome;
import ubic.gemma.model.genome.Taxon;
import ubic.gemma.model.genome.biosequence.BioSequence;
import ubic.gemma.model.genome.sequenceAnalysis.BlatResult;

import java.util.Arrays;
import java.util.Collections;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Formatting guards for the UCSC custom track emitted by {@link BlatResult2Psl}, which backs
 * {@code GET /platforms/{platform}/elements/{probe}/pslTrack}.
 */
public class BlatResult2PslTest {

    private static final String HOST = "https://gemma2.msl.ubc.ca";

    private static BlatResult blatResult( String chromosome, long targetStart, long targetEnd, int matches ) {
        Taxon taxon = Taxon.Factory.newInstance();
        taxon.setId( 1L );

        BioSequence chromosomeSequence = BioSequence.Factory.newInstance();
        chromosomeSequence.setLength( 248956422L );

        Chromosome chr = Chromosome.Factory.newInstance( chromosome, null, chromosomeSequence, taxon );

        BioSequence query = BioSequence.Factory.newInstance();
        query.setName( "AFFX_a" );
        query.setLength( 500L );

        BlatResult br = BlatResult.Factory.newInstance();
        br.setId( 5L );
        br.setQuerySequence( query );
        br.setTargetChromosome( chr );
        br.setMatches( matches );
        br.setMismatches( 2 );
        br.setRepMatches( 0 );
        br.setNs( 0 );
        br.setQueryGapCount( 0 );
        br.setQueryGapBases( 0 );
        br.setTargetGapCount( 1 );
        br.setTargetGapBases( 10 );
        br.setStrand( "+" );
        br.setQueryStart( 0 );
        br.setQueryEnd( 480 );
        br.setTargetStart( targetStart );
        br.setTargetEnd( targetEnd );
        br.setBlockCount( 2 );
        br.setBlockSizes( "200,280," );
        br.setQueryStarts( "0,200," );
        br.setTargetStarts( targetStart + "," + ( targetStart + 210 ) + "," );
        return br;
    }

    @Test
    public void trackCarriesProvenanceBrowserPositionAndOnePslLinePerAlignment() {
        String track = BlatResult2Psl.blatResults2PslTrack(
                Collections.singleton( blatResult( "1", 100000L, 100500L, 470 ) ), HOST, "AFFX_a" );

        String[] lines = track.split( "\n" );
        assertThat( lines[0] ).isEqualTo( "## Generated by Gemma (" + HOST + ")" );
        assertThat( lines[1] ).isEqualTo( "browser position chr1:99000-101500" );
        assertThat( lines[2] ).isEqualTo(
                "track name=\"AFFX_a\" description=\"Gemma BLAT alignment\" visibility=2 useScore=1" );
        // the 21 PSL columns, in UCSC order, TAB-delimited
        assertThat( lines[3].split( "\t" ) ).containsExactly(
                "470", "2", "0", "0", "0", "0", "1", "10", "+", "AFFX_a", "500", "0", "480",
                "chr1", "248956422", "100000", "100500", "2", "200,280,", "0,200,", "100000,100210," );
    }

    /**
     * A probe usually has several alignments and they are only useful side by side, so they share
     * one track. UCSC accepts a single {@code browser position}: it must frame the best-scoring
     * alignment, not whichever one the collection happened to iterate first.
     */
    @Test
    public void multipleAlignmentsShareOneTrackFramedOnTheBestScoring() {
        BlatResult weak = blatResult( "7", 5000L, 5400L, 300 );
        BlatResult best = blatResult( "12", 800000L, 800500L, 480 );

        String track = BlatResult2Psl.blatResults2PslTrack( Arrays.asList( weak, best ), HOST, "AFFX_a" );

        String[] lines = track.split( "\n" );
        assertThat( lines[1] ).isEqualTo( "browser position chr12:799000-801500" );
        assertThat( lines ).hasSize( 5 ); // provenance, position, track, 2 psl lines
        assertThat( lines[3] ).startsWith( "480\t" );
        assertThat( lines[4] ).startsWith( "300\t" );
    }

    /**
     * An alignment near the start of a chromosome would otherwise be framed at a negative
     * coordinate, which UCSC rejects.
     */
    @Test
    public void browserPositionIsClampedAtTheStartOfTheChromosome() {
        String track = BlatResult2Psl.blatResults2PslTrack(
                Collections.singleton( blatResult( "1", 300L, 800L, 470 ) ), HOST, "AFFX_a" );

        assertThat( track.split( "\n" )[1] ).isEqualTo( "browser position chr1:1-1800" );
    }

    @Test
    public void trackNameDefaultsToTheQuerySequenceName() {
        String track = BlatResult2Psl.blatResults2PslTrack(
                Collections.singleton( blatResult( "1", 100000L, 100500L, 470 ) ), HOST, null );

        assertThat( track.split( "\n" )[2] ).startsWith( "track name=\"AFFX_a\"" );
    }

    /**
     * The target size falls back to the target sequence, then to {@code targetEnd + 1}, when the
     * chromosome carries no sequence length -- the alignment is still placeable.
     */
    @Test
    public void targetSizeFallsBackWhenTheChromosomeHasNoSequenceLength() {
        BlatResult br = blatResult( "1", 100000L, 100500L, 470 );
        br.getTargetChromosome().setSequence( null );

        String track = BlatResult2Psl.blatResults2PslTrack( Collections.singleton( br ), HOST, "AFFX_a" );

        assertThat( track.split( "\n" )[3].split( "\t" )[14] ).isEqualTo( "100501" );
    }

    /**
     * Guards the ordering bug in the pre-exposure version: the target-chromosome null check sat
     * AFTER the line that dereferenced it, so a chromosome-less alignment produced an NPE from
     * deep inside the formatter rather than a statement of what was wrong.
     */
    @Test
    public void alignmentWithoutATargetChromosomeIsRefusedByName() {
        BlatResult br = blatResult( "1", 100000L, 100500L, 470 );
        br.setTargetChromosome( null );

        assertThatThrownBy( () -> BlatResult2Psl.blatResults2PslTrack(
                Collections.singleton( br ), HOST, "AFFX_a" ) )
                .isInstanceOf( IllegalArgumentException.class )
                .hasMessageContaining( "no target chromosome" );
    }

    @Test
    public void emptyAlignmentSetIsRefused() {
        assertThatThrownBy( () -> BlatResult2Psl.blatResults2PslTrack(
                Collections.emptyList(), HOST, "AFFX_a" ) )
                .isInstanceOf( IllegalArgumentException.class );
    }

    /**
     * The query name went out wrapped in literal double quotes from 2007 until 2026-08-22. UIB
     * measured what that does in UCSC: the item label in the track's left column renders as
     * {@code "1007_s_at_collapsed"}, quotes included, which is what a visitor reads. PSL has no
     * quoting convention -- the quotes were simply part of the field.
     */
    @Test
    public void queryNameIsNotQuoted() {
        String track = BlatResult2Psl.blatResults2PslTrack(
                Collections.singleton( blatResult( "1", 100000L, 100500L, 470 ) ), HOST, "AFFX_a" );

        assertThat( track.split( "\n" )[3].split( "\t" )[9] ).isEqualTo( "AFFX_a" );
        assertThat( track ).doesNotContain( "\"AFFX_a\"\t" );
    }

    /**
     * The track line keeps its quotes -- {@code track name="..."} is UCSC's own syntax for that
     * line, unlike the PSL data rows.
     */
    @Test
    public void trackLineKeepsItsQuotes() {
        String track = BlatResult2Psl.blatResults2PslTrack(
                Collections.singleton( blatResult( "1", 100000L, 100500L, 470 ) ), HOST, "AFFX_a" );

        assertThat( track.split( "\n" )[2] ).startsWith( "track name=\"AFFX_a\"" );
    }
}
