
Ext.namespace('Gemma');Gemma.SEARCH_FORM_WIDTH=900;Ext.BLANK_IMAGE_URL='/Gemma/images/default/s.gif';Ext.onReady(function(){Ext.QuickTips.init();Ext.state.Manager.setProvider(new Ext.state.CookieProvider());var admin=(Ext.get('hasAdmin')!==null)?Ext.get('hasAdmin').getValue():null;var user=(Ext.get('hasUser')!==null)?Ext.get('hasUser').getValue():null;var redirectToClassic=false;if(!document.createElement("canvas").getContext){redirectToClassic=true;if(Ext.isIE8){Ext.DomHelper.append('analysis-results-search-form',{tag:'p',cls:'trouble',id:'browserWarning',html:Gemma.HelpText.CommonWarnings.BrowserWarnings.ie8});}else if(Ext.isIE){Ext.DomHelper.append('analysis-results-search-form',{tag:'p',cls:'trouble',id:'browserWarning',html:Gemma.HelpText.CommonWarnings.BrowserWarnings.ieNot8});}else{Ext.DomHelper.append('analysis-results-search-form',{tag:'p',cls:'trouble',id:'browserWarning',html:Gemma.HelpText.CommonWarnings.BrowserWarnings.generic});}}
var searchPanel=new Gemma.AnalysisResultsSearchForm({width:Gemma.SEARCH_FORM_WIDTH,showClassicDiffExResults:redirectToClassic});this.diffVisualizer=null;searchPanel.render("analysis-results-search-form");searchPanel.checkUrlParams();this.resultsPanel=new Ext.TabPanel({id:'analysis-results-search-form-results-panel',height:610,defaults:{autoScroll:true,width:850},hidden:true});searchPanel.on("beforesearch",function(panel){var flashPanel=resultsPanel.getItem('cytoscaperesults');if(flashPanel){flashPanel.stopRender=true;}
this.resultsPanel.removeAll();this.resultsPanel.hide();panel.clearError();if(Ext.get('frontPageContent')){Ext.get('frontPageContent').remove();}
if(Ext.get('frontPageSlideShow')){Ext.get('frontPageSlideShow').remove();}
if(Ext.get('sloganText')){Ext.get('sloganText').remove();}
Ext.DomHelper.overwrite('meta-heatmap-div',{html:''});var tut=Ext.getCmp('tutorial-cntlPanel-diff-ex');if(tut){tut.hideTutorial();this.diffExTutorialAlreadyShown=true;}
tut=Ext.getCmp('tutorial-cntlPanel-coex');if(tut){tut.hideTutorial();this.coexTutorialAlreadyShown=true;}
if(redirectToClassic){document.getElementById('browserWarning').style.display="none";}},this);searchPanel.on("showCoexResults",function(panel,result,showCoexTutorial){resultsPanel.showCoexTutorial=showCoexTutorial;if(result.errorState){var errorPanel=new Ext.Panel({html:"<br> "+result.errorState,border:false,title:"No Coexpression Search Results"});resultsPanel.render('analysis-results-search-form-results');resultsPanel.add(errorPanel);resultsPanel.show();resultsPanel.doLayout();errorPanel.show();return;}
if(!knownGeneGrid){var coexpressionSearchData=new Gemma.CoexpressionSearchData({coexGridCoexCommand:searchPanel.getLastCoexpressionSearchCommand(),cytoscapeCoexCommand:Gemma.CytoscapePanelUtil.getCoexVizCommandFromCoexGridCommand(searchPanel.getLastCoexpressionSearchCommand()),coexGridResults:result});var displayedResults=Gemma.CoexValueObjectUtil.combineKnownGeneResultsAndQueryGeneOnlyResults(result.knownGeneResults,result.queryGenesOnlyResults);var highestResultStringency=Gemma.CoexValueObjectUtil.getHighestResultStringencyUpToInitialDisplayStringency(displayedResults,coexpressionSearchData.coexGridCoexCommand.displayStringency);if(coexpressionSearchData.coexGridCoexCommand.displayStringency>highestResultStringency){coexpressionSearchData.coexGridCoexCommand.displayStringency=highestResultStringency;coexpressionSearchData.cytoscapeCoexCommand.displayStringency=highestResultStringency;coexpressionSearchData.cytoscapeCoexCommand.stringency=Gemma.CytoscapePanelUtil.restrictResultsStringency(highestResultStringency);}
var knownGeneGrid=new Gemma.CoexpressionGrid({width:900,height:400,title:"Table",ref:'coexGridResults',id:'coexGridResults',colspan:2,user:user,tabPanelViewFlag:true,layoutOnTabChange:true,hideMode:'offsets',coexpressionSearchData:coexpressionSearchData});}
var cytoscapePanel=new Gemma.CytoscapePanel({id:"cytoscaperesults",ref:'coexCytoscapeResults',title:"Visualization",width:850,taxonId:searchPanel.getTaxonId(),taxonName:searchPanel.getTaxonName(),hideMode:'visibility',coexpressionSearchData:coexpressionSearchData,knownGeneGrid:knownGeneGrid,searchPanel:searchPanel});if(showCoexTutorial){setupCoexTutorial(resultsPanel,knownGeneGrid,cytoscapePanel);}
panel.collapsePreviews();resultsPanel.add(knownGeneGrid);resultsPanel.add(cytoscapePanel);resultsPanel.render('analysis-results-search-form-results');resultsPanel.show();resultsPanel.doLayout();knownGeneGrid.loadData(result.isCannedAnalysis,2,displayedResults,result.knownGeneDatasets);knownGeneGrid.refreshGridFromCoexpressionSearchData();knownGeneGrid.show();});var setupCoexTutorial=function(resultsPanel,knownGeneGrid,cytoscapePanel){if(this.coexTutorialControlPanel){this.coexTutorialControlPanel.destroy();}
var tutorialControlPanel=new Gemma.Tutorial.ControlPanel({renderTo:'tutorial-control-div',id:'tutorial-cntlPanel-coex',});this.coexTutorialControlPanel=tutorialControlPanel;if(!tutorialControlPanel.hidden){var tipDefs=[];tipDefs.push({element:knownGeneGrid.getTopToolbar().stringencyfield,title:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.stringencyTitle,text:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.stringencyText});tipDefs.push({element:knownGeneGrid.getTopToolbar().arbitraryTutorialTooltip2,title:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.supportColumnTitle,text:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.supportColumnText});tipDefs.push({element:knownGeneGrid.getTopToolbar().arbitraryTutorialTooltip3,title:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.nodeDegreeColumnTitle,text:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.nodeDegreeColumnText});tipDefs.push({element:knownGeneGrid.getTopToolbar().searchInGrid,title:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.visualizeTabTitle,text:Gemma.HelpText.WidgetDefaults.AnalysisResultsSearchNonWidget.CoexpressionTutorial.visualizeTabText,position:{moveDown:-25}});tutorialControlPanel.addTips(tipDefs);}
resultsPanel.on('afterlayout',function(){if(!resultsPanel.tutorialStarted&&resultsPanel.showCoexTutorial){this.coexTutorialControlPanel.show();this.coexTutorialControlPanel.playTips(0);resultsPanel.on('beforetabchange',function(tabPanel,newTab,currTab){this.coexTutorialControlPanel.hideTips(this.coexTutorialControlPanel.tips);this.coexTutorialControlPanel.hide();if(newTab&&newTab.id=='cytoscaperesults'){resultsPanel.showCoexTutorial=false;}},this);}},this);this.coexTutorialControlPanel.on('tutorialHidden',function(){this.coexTutorialControlPanel.hide();this.coexTutorialControlPanel.hidden=true;},this);};searchPanel.on("showDiffExResults",function(panel,result,data){if(!redirectToClassic){Ext.apply(data,{applyTo:'meta-heatmap-div'});this.diffVisualizer=new Gemma.MetaHeatmapDataSelection(data);this.diffVisualizer.on('visualizationLoaded',function(){panel.loadMask.hide();},this);}
else{var flashPanel=resultsPanel.getItem('cytoscaperesults');if(flashPanel){flashPanel.stopRender=true;}
this.resultsPanel.removeAll();this.resultsPanel.hide();var diffExResultsGrid=new Gemma.DiffExpressionGrid({renderTo:'meta-heatmap-div',title:"Differentially expressed genes",searchPanel:searchPanel,viewConfig:{forceFit:true},width:'auto',style:'width:100%'});diffExResultsGrid.loadData(result);var link=panel.getDiffExBookmarkableLink();diffExResultsGrid.setTitle(String.format("Differentially expressed genes <a target='_blank' href='{0}&export'>(export as text)</a>",link));}},this);});