/*
 * The Gemma project.
 * 
 * Copyright (c) 2006-2007 University of British Columbia
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package ubic.gemma.model.common.auditAndSecurity.eventType;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find objects of type
 * <code>ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent</code>.
 * </p>
 * 
 * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent
 */
public abstract class TooSmallDatasetLinkAnalysisEventDaoBase extends
        ubic.gemma.model.common.auditAndSecurity.eventType.LinkAnalysisEventDaoImpl implements
        ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao {

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#load(int,
     *      java.lang.Long)
     */
    @Override
    public Object load( final int transform, final java.lang.Long id ) {
        if ( id == null ) {
            throw new IllegalArgumentException( "TooSmallDatasetLinkAnalysisEvent.load - 'id' can not be null" );
        }
        final Object entity = this.getHibernateTemplate().get(
                ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventImpl.class, id );
        return transformEntity( transform,
                ( ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent ) entity );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#load(java.lang.Long)
     */
    @Override
    public ubic.gemma.model.common.auditAndSecurity.eventType.AuditEventType load( java.lang.Long id ) {
        return ( ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent ) this.load(
                TRANSFORM_NONE, id );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#loadAll()
     */
    @Override
    @SuppressWarnings( { "unchecked" })
    public java.util.Collection loadAll() {
        return this.loadAll( TRANSFORM_NONE );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#loadAll(int)
     */
    @Override
    public java.util.Collection loadAll( final int transform ) {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(
                ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventImpl.class );
        this.transformEntities( transform, results );
        return results;
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#create(ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent)
     */
    public ubic.gemma.model.common.auditAndSecurity.eventType.AuditEventType create(
            ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent tooSmallDatasetLinkAnalysisEvent ) {
        return ( ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent ) this.create(
                TRANSFORM_NONE, tooSmallDatasetLinkAnalysisEvent );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#create(int transform,
     *      ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent)
     */
    public Object create(
            final int transform,
            final ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent tooSmallDatasetLinkAnalysisEvent ) {
        if ( tooSmallDatasetLinkAnalysisEvent == null ) {
            throw new IllegalArgumentException(
                    "TooSmallDatasetLinkAnalysisEvent.create - 'tooSmallDatasetLinkAnalysisEvent' can not be null" );
        }
        this.getHibernateTemplate().save( tooSmallDatasetLinkAnalysisEvent );
        return this.transformEntity( transform, tooSmallDatasetLinkAnalysisEvent );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#create(java.util.Collection)
     */
    @Override
    @SuppressWarnings( { "unchecked" })
    public java.util.Collection create( final java.util.Collection entities ) {
        return create( TRANSFORM_NONE, entities );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#create(int,
     *      java.util.Collection)
     */
    @Override
    public java.util.Collection create( final int transform, final java.util.Collection entities ) {
        if ( entities == null ) {
            throw new IllegalArgumentException( "TooSmallDatasetLinkAnalysisEvent.create - 'entities' can not be null" );
        }
        this.getHibernateTemplate().execute( new org.springframework.orm.hibernate3.HibernateCallback() {
            public Object doInHibernate( org.hibernate.Session session ) throws org.hibernate.HibernateException {
                for ( java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext(); ) {
                    create(
                            transform,
                            ( ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent ) entityIterator
                                    .next() );
                }
                return null;
            }
        }, true );
        return entities;
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#update(ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent)
     */
    public void update(
            ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent tooSmallDatasetLinkAnalysisEvent ) {
        if ( tooSmallDatasetLinkAnalysisEvent == null ) {
            throw new IllegalArgumentException(
                    "TooSmallDatasetLinkAnalysisEvent.update - 'tooSmallDatasetLinkAnalysisEvent' can not be null" );
        }
        this.getHibernateTemplate().update( tooSmallDatasetLinkAnalysisEvent );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.AuditEventTypeDao#update(java.util.Collection)
     */
    @Override
    public void update( final java.util.Collection entities ) {
        if ( entities == null ) {
            throw new IllegalArgumentException( "TooSmallDatasetLinkAnalysisEvent.update - 'entities' can not be null" );
        }
        this.getHibernateTemplate().execute( new org.springframework.orm.hibernate3.HibernateCallback() {
            public Object doInHibernate( org.hibernate.Session session ) throws org.hibernate.HibernateException {
                for ( java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext(); ) {
                    update( ( ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent ) entityIterator
                            .next() );
                }
                return null;
            }
        }, true );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#remove(ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent)
     */
    public void remove(
            ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent tooSmallDatasetLinkAnalysisEvent ) {
        if ( tooSmallDatasetLinkAnalysisEvent == null ) {
            throw new IllegalArgumentException(
                    "TooSmallDatasetLinkAnalysisEvent.remove - 'tooSmallDatasetLinkAnalysisEvent' can not be null" );
        }
        this.getHibernateTemplate().delete( tooSmallDatasetLinkAnalysisEvent );
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao#remove(java.lang.Long)
     */
    @Override
    public void remove( java.lang.Long id ) {
        if ( id == null ) {
            throw new IllegalArgumentException( "TooSmallDatasetLinkAnalysisEvent.remove - 'id' can not be null" );
        }
        ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent entity = ( ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent ) this
                .load( id );
        if ( entity != null ) {
            this.remove( entity );
        }
    }

    /**
     * @see ubic.gemma.model.common.auditAndSecurity.eventType.AuditEventTypeDao#remove(java.util.Collection)
     */
    @Override
    public void remove( java.util.Collection entities ) {
        if ( entities == null ) {
            throw new IllegalArgumentException( "TooSmallDatasetLinkAnalysisEvent.remove - 'entities' can not be null" );
        }
        this.getHibernateTemplate().deleteAll( entities );
    }

    /**
     * Allows transformation of entities into value objects (or something else for that matter), when the
     * <code>transform</code> flag is set to one of the constants defined in
     * <code>ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao</code>, please
     * note that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself will be returned.
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     * 
     * @param transform one of the constants declared in
     *        {@link ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected Object transformEntity( final int transform,
            final ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent entity ) {
        Object target = null;
        if ( entity != null ) {
            switch ( transform ) {
                case TRANSFORM_NONE: // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent)}
     * method. This method does not instantiate a new collection. <p/> This method is to be used internally only.
     * 
     * @param transform one of the constants declared in
     *        <code>ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEventDao</code>
     * @param entities the collection of entities to transform
     * @return the same collection as the argument, but this time containing the transformed entities
     * @see #transformEntity(int,ubic.gemma.model.common.auditAndSecurity.eventType.TooSmallDatasetLinkAnalysisEvent)
     */
    @Override
    protected void transformEntities( final int transform, final java.util.Collection entities ) {
        switch ( transform ) {
            case TRANSFORM_NONE: // fall-through
            default:
                // do nothing;
        }
    }

}