/*
 * The Gemma project.
 * 
 * Copyright (c) 2006-2007 University of British Columbia
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringServiceBase.vsl in andromda-spring-cartridge.
//
package ubic.gemma.model.genome;

/**
 * <p>
 * Spring Service base class for <code>ubic.gemma.model.genome.TaxonService</code>, provides access to all services
 * and entities referenced by this service.
 * </p>
 * 
 * @see ubic.gemma.model.genome.TaxonService
 */
public abstract class TaxonServiceBase implements ubic.gemma.model.genome.TaxonService {

    private ubic.gemma.model.genome.TaxonDao taxonDao;

    /**
     * Sets the reference to <code>taxon</code>'s DAO.
     */
    public void setTaxonDao( ubic.gemma.model.genome.TaxonDao taxonDao ) {
        this.taxonDao = taxonDao;
    }

    /**
     * Gets the reference to <code>taxon</code>'s DAO.
     */
    protected ubic.gemma.model.genome.TaxonDao getTaxonDao() {
        return this.taxonDao;
    }

    /**
     * @see ubic.gemma.model.genome.TaxonService#find(ubic.gemma.model.genome.Taxon)
     */
    public ubic.gemma.model.genome.Taxon find( final ubic.gemma.model.genome.Taxon taxon ) {
        try {
            return this.handleFind( taxon );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.find(ubic.gemma.model.genome.Taxon taxon)' --> "
                            + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #find(ubic.gemma.model.genome.Taxon)}
     */
    protected abstract ubic.gemma.model.genome.Taxon handleFind( ubic.gemma.model.genome.Taxon taxon )
            throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#update(ubic.gemma.model.genome.Taxon)
     */
    public void update( final ubic.gemma.model.genome.Taxon taxon ) {
        try {
            this.handleUpdate( taxon );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.update(ubic.gemma.model.genome.Taxon taxon)' --> "
                            + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #update(ubic.gemma.model.genome.Taxon)}
     */
    protected abstract void handleUpdate( ubic.gemma.model.genome.Taxon taxon ) throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#remove(ubic.gemma.model.genome.Taxon)
     */
    public void remove( final ubic.gemma.model.genome.Taxon taxon ) {
        try {
            this.handleRemove( taxon );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.remove(ubic.gemma.model.genome.Taxon taxon)' --> "
                            + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #remove(ubic.gemma.model.genome.Taxon)}
     */
    protected abstract void handleRemove( ubic.gemma.model.genome.Taxon taxon ) throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#findOrCreate(ubic.gemma.model.genome.Taxon)
     */
    public ubic.gemma.model.genome.Taxon findOrCreate( final ubic.gemma.model.genome.Taxon taxon ) {
        try {
            return this.handleFindOrCreate( taxon );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.findOrCreate(ubic.gemma.model.genome.Taxon taxon)' --> "
                            + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #findOrCreate(ubic.gemma.model.genome.Taxon)}
     */
    protected abstract ubic.gemma.model.genome.Taxon handleFindOrCreate( ubic.gemma.model.genome.Taxon taxon )
            throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#loadAll()
     */
    public java.util.Collection loadAll() {
        try {
            return this.handleLoadAll();
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.loadAll()' --> " + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #loadAll()}
     */
    protected abstract java.util.Collection handleLoadAll() throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#findByScientificName(java.lang.String)
     */
    public ubic.gemma.model.genome.Taxon findByScientificName( final java.lang.String scientificName ) {
        try {
            return this.handleFindByScientificName( scientificName );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.findByScientificName(java.lang.String scientificName)' --> "
                            + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #findByScientificName(java.lang.String)}
     */
    protected abstract ubic.gemma.model.genome.Taxon handleFindByScientificName( java.lang.String scientificName )
            throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#findByCommonName(java.lang.String)
     */
    public ubic.gemma.model.genome.Taxon findByCommonName( final java.lang.String commonName ) {
        try {
            return this.handleFindByCommonName( commonName );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.findByCommonName(java.lang.String commonName)' --> "
                            + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #findByCommonName(java.lang.String)}
     */
    protected abstract ubic.gemma.model.genome.Taxon handleFindByCommonName( java.lang.String commonName )
            throws java.lang.Exception;

    /**
     * @see ubic.gemma.model.genome.TaxonService#load(java.lang.Long)
     */
    public ubic.gemma.model.genome.Taxon load( final java.lang.Long id ) {
        try {
            return this.handleLoad( id );
        } catch ( Throwable th ) {
            throw new ubic.gemma.model.genome.TaxonServiceException(
                    "Error performing 'ubic.gemma.model.genome.TaxonService.load(java.lang.Long id)' --> " + th, th );
        }
    }

    /**
     * Performs the core logic for {@link #load(java.lang.Long)}
     */
    protected abstract ubic.gemma.model.genome.Taxon handleLoad( java.lang.Long id ) throws java.lang.Exception;

    /**
     * Gets the current <code>principal</code> if one has been set, otherwise returns <code>null</code>.
     * 
     * @return the current principal
     */
    protected java.security.Principal getPrincipal() {
        return ubic.gemma.spring.PrincipalStore.get();
    }

    /**
     * Gets the message source available to this service.
     */
    protected org.springframework.context.MessageSource getMessages() {
        return ( org.springframework.context.MessageSource ) ubic.gemma.spring.BeanLocator.instance().getBean(
                "messageSource" );
    }

    /**
     * Gets the message having the given <code>key</code> in the underlying message bundle.
     * 
     * @param key the key of the message in the messages.properties message bundle.
     */
    protected String getMessage( final String key ) {
        return this.getMessages().getMessage( key, null, null );
    }

    /**
     * Gets the message having the given <code>key</code> and <code>arguments</code> in the underlying message
     * bundle.
     * 
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     */
    protected String getMessage( final String key, final Object[] arguments ) {
        return this.getMessages().getMessage( key, arguments, null );
    }

    /**
     * Gets the message having the given <code>key</code> using the given <code>arguments</code> for the given
     * <code>locale</code>.
     * 
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @param locale the locale of the messages to retrieve.
     */
    protected String getMessage( final java.lang.String key, final java.lang.Object[] arguments,
            final java.util.Locale locale ) {
        return this.getMessages().getMessage( key, arguments, locale );
    }

}