package ubic.gemma.core.ontology.providers.chebi;

import org.apache.jena.ontology.OntClass;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.util.iterator.ExtendedIterator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import ubic.gemma.core.ontology.providers.OntologySlimExtractor;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.zip.GZIPInputStream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises {@link OntologySlimExtractor} against real-shaped CHEBI fixtures generated
 * via ROBOT STAR extraction from upstream CHEBI ({@code chebi-mini-medium.test.owl},
 * 365 KB, from chebi_lite) and from the heavyweight full CHEBI ({@code
 * chebi-mini-medium-from-full.test.owl.gz}, 1.4 MB raw, carries the chemical-structure
 * annotation axioms that chebi_lite drops). Pins the reduction ratio + Jena
 * round-trip on shapes much closer to production than the 8-class
 * hand-rolled fixture covered by {@code OntologySlimExtractorTest}.
 *
 * <p>Each test asserts:
 * <ul>
 *   <li>The slim file is at least ~3× smaller than the source by byte count.</li>
 *   <li>The seed term itself is present.</li>
 *   <li>STAR-expanded ancestors are present (so {@code getParents()} works on the slim).</li>
 *   <li>Jena can parse the slim cleanly (it's the runtime load path).</li>
 * </ul>
 *
 * <p>Both fixtures live under {@code data/loader/ontology/} and were generated by
 * {@code ~/chebi-fixtures/build-mini-chebi.sh} on frink — re-run that script when CHEBI
 * upstream rolls a new release if the fixtures need refreshing.
 */
class OntologySlimExtractorChebiFixtureTest {

    private static final String CHEBI_LITE_MEDIUM = "/data/loader/ontology/chebi-mini-medium.test.owl";
    private static final String FULL_DERIVED_MEDIUM_GZ =
            "/data/loader/ontology/chebi-mini-medium-from-full.test.owl.gz";

    // Seed: just a couple of CHEBI URIs from inside the medium fixture's coverage.
    private static final String ANTINEOPLASTIC = "http://purl.obolibrary.org/obo/CHEBI_35610";
    private static final String IMMUNOSUPPRESSANT = "http://purl.obolibrary.org/obo/CHEBI_35470";
    private static final String ROLE = "http://purl.obolibrary.org/obo/CHEBI_50906";

    @Test
    void slimFromChebiLiteShapedFixtureShrinksAtLeast3x( @TempDir Path tempDir ) throws Exception {
        File source = copyClasspathResource( CHEBI_LITE_MEDIUM, tempDir, "chebi-source.owl" );
        long sourceBytes = source.length();
        File slim = tempDir.resolve( "slim.owl" ).toFile();

        OntologySlimExtractor.ExtractResult result = new OntologySlimExtractor()
                .extract( source, List.of( ANTINEOPLASTIC ), slim );

        long slimBytes = slim.length();
        // Observed on 2026-05-26: 67× reduction (365 KB → 5.5 KB) for a 1-term seed
        // against the chebi_lite-shaped medium fixture. Assert ≥20× as a robust
        // regression floor that survives minor fixture-regeneration drift but still
        // catches a real shrinkage failure.
        assertTrue( slimBytes * 20 < sourceBytes,
                "slim must be at least 20x smaller than source: source=" + sourceBytes
                        + " bytes, slim=" + slimBytes + " bytes ("
                        + ( (double) sourceBytes / slimBytes ) + "x)" );

        // Behavioural assertion: the seed and its ancestors round-trip through Jena.
        Set<String> jenaClasses = loadClassUrisViaJena( slim );
        assertTrue( jenaClasses.contains( ANTINEOPLASTIC ), "seed retained: antineoplastic" );
        assertTrue( jenaClasses.contains( ROLE ), "STAR-expanded ancestor retained: role" );

        // Spot the meta: extractor reported a sane class count.
        assertTrue( result.getClassCount() > 0 );
    }

    @Test
    void slimFromFullDerivedFixtureShrinksAtLeast3xAndJenaParses( @TempDir Path tempDir ) throws Exception {
        // The full-derived fixture is gzipped at-rest because it's larger. Inflate first.
        File source = inflateClasspathResource( FULL_DERIVED_MEDIUM_GZ, tempDir, "chebi-source.owl" );
        long sourceBytes = source.length();
        File slim = tempDir.resolve( "slim.owl" ).toFile();

        new OntologySlimExtractor().extract( source, List.of( ANTINEOPLASTIC, IMMUNOSUPPRESSANT ), slim );

        long slimBytes = slim.length();
        // Observed on 2026-05-26: 119× reduction (1.4 MB → 12 KB) for a 2-term seed
        // against the full-derived medium fixture. The chemical-structure annotation
        // axioms (formula, inchi_key, inchi_string, smiles) don't apply to retained
        // role classes, so STAR drops them naturally. Assert ≥30× as a regression
        // floor (slightly looser than the chebi_lite test because the source has
        // more annotation noise that could land in the module on a seed change).
        assertTrue( slimBytes * 30 < sourceBytes,
                "slim must be at least 30x smaller: source=" + sourceBytes
                        + " bytes, slim=" + slimBytes + " bytes ("
                        + ( (double) sourceBytes / slimBytes ) + "x)" );

        // Jena must consume the output as a runtime ontology — this is the same path
        // ChebiOntologyService.loadModel takes on a slim-cache hit.
        OntModel jenaModel = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM );
        try ( FileInputStream in = new FileInputStream( slim ) ) {
            jenaModel.read( in, null );
        }
        OntClass antineoplastic = jenaModel.getOntClass( ANTINEOPLASTIC );
        OntClass immunosuppressant = jenaModel.getOntClass( IMMUNOSUPPRESSANT );
        assertNotNull( antineoplastic, "antineoplastic OntClass round-trips through Jena" );
        assertNotNull( immunosuppressant, "immunosuppressant OntClass round-trips through Jena" );
        assertTrue( antineoplastic.getLabel( null ) != null && !antineoplastic.getLabel( null ).isEmpty(),
                "rdfs:label preserved on retained class" );
    }

    private File copyClasspathResource( String classpath, Path tempDir, String outName ) throws IOException {
        File out = tempDir.resolve( outName ).toFile();
        try ( InputStream in = getClass().getResourceAsStream( classpath ) ) {
            assertNotNull( in, "fixture not on classpath: " + classpath );
            Files.copy( in, out.toPath() );
        }
        return out;
    }

    private File inflateClasspathResource( String classpath, Path tempDir, String outName ) throws IOException {
        File out = tempDir.resolve( outName ).toFile();
        try ( InputStream raw = getClass().getResourceAsStream( classpath );
              GZIPInputStream in = new GZIPInputStream( raw ) ) {
            assertNotNull( raw, "fixture not on classpath: " + classpath );
            Files.copy( in, out.toPath() );
        }
        return out;
    }

    private Set<String> loadClassUrisViaJena( File owl ) throws IOException {
        OntModel m = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM );
        try ( FileInputStream in = new FileInputStream( owl ) ) {
            m.read( in, null );
        }
        Set<String> uris = new HashSet<>();
        ExtendedIterator<OntClass> it = m.listClasses();
        while ( it.hasNext() ) {
            OntClass c = it.next();
            if ( c.getURI() != null ) {
                uris.add( c.getURI() );
            }
        }
        it.close();
        return uris;
    }
}
